import Head from 'next/head'
import { BiUserPlus } from 'react-icons/bi'
import Table from '../components/table'
import Form from '../components/form'
import { useState } from 'react'
import {useSelector,useDispatch} from 'react-redux'
import {toggleChangeAction} from '../redux/reducer'


export default function Home() {
  const visible = useSelector((state) => state.app.client.toggleForm)
  const dispatch = useDispatch()


  const handler = () =>{
    dispatch(toggleChangeAction) 
  }

  return (
    <section >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <h1 className='text-xl md:text-5xl text-center font-bold py-10'>predios</h1>
      <div className='container mx-auto flex justify-between py-4 border-b'>
        
       <div className='left-flex'>
       <button onClick={handler} className='flex bg-indigo-500 text-white px-2 py-1 border rounded-md hover:bg-grary-50 hover:boder-indigo-800 hover:text-gray-700 '>
          add predio<span className='px-1.5'><BiUserPlus size={24}></BiUserPlus></span>
        </button>
       </div>
       </div>

      {/*collapsable form*/}
      
     {visible ? <Form></Form>:<></>}
     

    
    {/*table*/}
    <div className="container mx-auto">
     <Table></Table>
     </div>
      </main>

    </section>
  )
}
